    - name: Install dependencies
      ansible.builtin.package:
        name: "{{item}}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Add GPG-key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      ansible.builtin.package:
        name: "{{item}}"
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io

