#Docker
- name: Install Docker
  hosts: app
  tasks:
    - include_tasks: rhel.yaml
      when: ansible_os_family == 'RedHat'

    - include_tasks: debian.yaml
      when: ansible_os_family == 'Debian'
